version: "3.7"
services:
  app:
    container_name: project-3-the-scoop-test
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm run test"